import { resolve } from 'node:path'

const root = resolve(import.meta.dir, '..')
const result = await Bun.build({
  entrypoints: [resolve(root, 'src/apps/ui/app.ts')],
  target: 'browser',
  minify: true,
})
if (!result.success) throw new AggregateError(result.logs, 'MCP App build failed')
const js = (await result.outputs[0].text()).replaceAll('</script', '<\\/script')
const css = await Bun.file(resolve(root, 'src/apps/ui/app.css')).text()
const html = `<!-- Generated by bun run build:app; edit src/apps/ui instead. -->
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light dark"><title>Durabull · Queue explorer</title><style>${css}</style></head><body><main id="app" aria-label="Durabull queue explorer"><div class="empty" role="status">Connecting to Durabull…</div></main><script type="module">${js}</script></body></html>\n`
const target = Bun.file(resolve(root, 'src/apps/dashboard.generated.txt'))
if (process.argv.includes('--check')) {
  if (!(await target.exists()) || (await target.text()) !== html) {
    throw new Error('MCP App bundle is stale. Run bun run --cwd packages/mcp build:app.')
  }
} else {
  await Bun.write(target, html)
}
console.info(
  `MCP App ${process.argv.includes('--check') ? 'verified' : 'built'} (${Math.round(html.length / 1024)} KB)`
)
