import { resolve } from 'node:path'
import { bundleMcpApp } from './bundle-app'

const root = resolve(import.meta.dir, '..')
const { html: document } = await bundleMcpApp()
const html = `<!-- Generated by bun run build:app; edit src/apps/ui instead. -->\n${document}\n`
const target = Bun.file(resolve(root, 'src/apps/dashboard.generated.txt'))
if (process.argv.includes('--check')) {
  if (!(await target.exists()) || (await target.text()) !== html) {
    throw new Error('MCP App bundle is stale. Run bun run --cwd packages/mcp build:app.')
  }
} else {
  await Bun.write(target, html)
}
console.info(
  `MCP App ${process.argv.includes('--check') ? 'verified' : 'built'} (${Math.round(html.length / 1024)} KB)`
)
